name = "lyrics-worker"
type = "javascript"
account_id = "your-cloudflare-account-id"
compatibility_date = "2025-06-10"

[[d1_databases]]
binding = "DB"
database_name = "lyrics_db"
id = "1da90d4c-2ada-4c8c-88e0-fb329b600ecc"
